name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间23点0分，北京时间需要+8小时，代表北京时间上午7点运行
    - cron: '0 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 如果需要，可以指定node版本
          node-version: '20'
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          # 如果需要，可以指定node版本
          node-version: '20'
      
      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weixin script
        run: |
          python main.py




